version: "3"

services:
  iamrole_service:
    build: 
      context: ./fake_dependencies/iamrole_service
    ports:
      - "50800:50800"
  rolemapper_service:
    build: 
      context: ./fake_dependencies/rolemapper_service
    ports:
      - "50801:50801"