version: '3.4'

services:
  capability-service.webapi:
    build:
      context: .
      dockerfile: src/CapabilityService.WebApi/Dockerfile
    environment:
      - "CAPABILITYSERVICE_DATABASE_CONNECTIONSTRING=User ID=postgres;Password=p;Host=database;Port=5432;Database=capabilitydb;"
      
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=p"

  db-migration:
    build: 
      context: ./db
      dockerfile: Dockerfile
    depends_on:
      - database
    # volumes:
    #   - ${PWD}/db/export:/tmp
    environment:
      # - DEBUG=1                     # enable script debugging
      - "LOCAL_DEVELOPMENT=1"         # will try to CREATE DATABASE ${PGDATABASE}
      - "PGDATABASE=capabilitydb"     # database name
      - "PGHOST=database"             # same as avove - docker-compose service name
      - "PGPORT=5432"                 # same as above
      - "PGUSER=postgres"             # same as above
      - "PGPASSWORD=p"                # same as above
      - "PGSSLMODE=disable"           # ignore SSLMODE for local development (overwritten - see ./db/Dockerfile)

  messagebroker:
    hostname: kafka
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - "ADVERTISED_HOST=kafka"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"