version: '3.5'

services:

  database:
    image: postgres:latest
    ports:
      - "1433:5432"
    restart: always
    networks:
      - bridge-network
    environment:
    - POSTGRES_USER=1
    - POSTGRES_PASSWORD=1


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8088:80"
    networks:
      - bridge-network
    restart: always
    environment:
    - PGADMIN_DEFAULT_EMAIL=e
    - PGADMIN_DEFAULT_PASSWORD=p


  team-api:
    build: .
    ports: 
      - "8080:80"
    networks:
      - bridge-network
    environment:
    - VALIDATE_ENVIRONMENT_VARIABLES=false
    - TEAM_DATABASE_CONNECTIONSTRING='Host=database;Username=postgres;Password=p;Database=team-database'
      

networks:
  bridge-network:
    driver: bridge