version: '3.5'

services:
  database:
    image: postgres:latest
    networks:
      development:
        aliases:
          - database
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=p"

  db-migration:
    build: 
      context: ./db
      dockerfile: Dockerfile    
    networks:
      development:
        aliases:
          - db-migration
    depends_on:
      - database
    # volumes:
    #   - ${PWD}/db/export:/tmp
    environment:
      #- "DEBUG=1"                     # enable script debugging
      - "LOCAL_DEVELOPMENT=1"         # will try to CREATE DATABASE ${PGDATABASE}
      - "PGDATABASE=capabilitydb"     # database name
      - "PGHOST=database"             # same as avove - docker-compose service name
      - "PGPORT=5432"                 # same as above
      - "PGUSER=postgres"             # same as above
      - "PGPASSWORD=p"                # same as above
      - "PGSSLMODE=disable"           # ignore SSLMODE for local development (overwritten - see ./db/Dockerfile)

  kafka:
    hostname: kafka
    image: spotify/kafka    
    networks:
      development:
        aliases:
          - kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - "ADVERTISED_HOST=127.0.0.1"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"

networks:
  development:
    name: development