version: '3.5'

services:

  database:
    image: postgres:latest
    restart: always
    networks:
      - bridge-network
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=p


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8088:80"
    networks:
      - bridge-network
    restart: always
    environment:
    - PGADMIN_DEFAULT_EMAIL=e
    - PGADMIN_DEFAULT_PASSWORD=p


  team-api:
    build: .
    ports: 
      - "8080:80"
    networks:
      - bridge-network
    environment:
      

networks:
  bridge-network:
    driver: bridge