version: '3.5'

services:
  capability-service.webapi:
    hostname: capability-service
    build:
      context: .
      dockerfile: Dockerfile-CapabilityService.WebApi 
    networks:
      development:
        aliases:
          - capability-service
    ports:
      - "50900:50900"
      - "8080:8080"
    depends_on:
      - db-migration
      - kafka
    environment:
      - "CAPABILITYSERVICE_DATABASE_CONNECTIONSTRING=User ID=postgres;Password=p;Host=database;Port=5432;Database=capabilitydb;"
      - "CAPABILITY_SERVICE_KAFKA_BOOTSTRAP_SERVERS=kafka:9092"
      - "CAPABILITY_SERVICE_KAFKA_GROUP_ID=capability-service-consumer"
      - "CAPABILITY_SERVICE_KAFKA_TOPIC_CAPABILITY=build.selfservice.events.capabilities"
      - "CAPABILITY_SERVICE_KAFKA_TOPIC_TOPICS=build.selfservice.events.topics"
      - "CAPABILITY_SERVICE_KAFKA_ENABLE_AUTO_COMMIT=false"
      - "ASPNETCORE_URLS=http://+:50900"
      
  database:
    image: postgres:latest
    networks:
      development:
        aliases:
          - database
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=p"

  db-migration:
    build: 
      context: ./db
      dockerfile: Dockerfile    
    networks:
      development:
        aliases:
          - db-migration
    depends_on:
      - database
    # volumes:
    #   - ${PWD}/db/export:/tmp
    environment:
      #- "DEBUG=1"                     # enable script debugging
      - "LOCAL_DEVELOPMENT=1"         # will try to CREATE DATABASE ${PGDATABASE}
      - "PGDATABASE=capabilitydb"     # database name
      - "PGHOST=database"             # same as avove - docker-compose service name
      - "PGPORT=5432"                 # same as above
      - "PGUSER=postgres"             # same as above
      - "PGPASSWORD=p"                # same as above
      - "PGSSLMODE=disable"           # ignore SSLMODE for local development (overwritten - see ./db/Dockerfile)

  kafka:
    hostname: kafka
    image: spotify/kafka    
    networks:
      development:
        aliases:
          - kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - "ADVERTISED_HOST=kafka"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"

networks:
  development:
    name: development