version: '3'

services:
  database:
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=p

  db-migration:
    build: ./db
    depends_on:
    - database
    environment:
    - LOCAL_DEVELOPMENT=1       # will try top CREATE DATABASE ${PGDATABASE}
    - PGDATABASE=teamservice    # database name
    - PGHOST=database           # same as avove - docker-compose service name
    - PGPORT=5432               # same as above
    - PGUSER=postgres           # same as above
    - PGPASSWORD=p              # same as above
    - PGSSLMODE=disable         # ignore SSLMODE for local development (overwritten - see ./db/Dockerfile)
