apiVersion: v1
kind: Secret
metadata:
  name: capabilityservice-basic-authentication-credentials
  namespace: selfservice
  labels:
    project: selfservice
    department: devex
    app: team-service
type: Opaque
stringData:
  auth: "iTooLikeSecurity"

---

apiVersion: v1
kind: Secret
metadata:
  name: capability-service-db
  namespace: selfservice
  labels:
    project: selfservice
    department: devex
    app: team-service
type: Opaque
stringData:
  password: "iTooLikeSecurity"
  connection-string: "User ID=postgres;Password=p;Host=capability-service-db;Port=5432;Database=ts"