swagger: '2.0'
info:
  version: 0.0.1
  title: Capability Service
  description: The authority of all things CAPABILITY related!
consumes:
  - application/json
produces:
  - application/json
schemes: 
  - http
host: localhost:5000
basePath: /api/v1/
tags:
  - name: capability
    description: access single or multiple capabilities
  - name: membership
    description: start and stop memberships for members
  - name: context
    description: access to capability contexts
  - name: topic
    description: manage topics for a capability
paths:
  /capabilities: 
    get:
      summary: Returns a list of capabilities
      tags:
        - capability
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/capability-list'
    post:
      summary: Create a new capability
      tags:
        - capability
      parameters: 
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
      responses:
        '201':
          description: Created
          headers:
            location:
              type: string
              description: URI where the capability can be retrieved
          schema:
            $ref: '#/definitions/capability'
        '400':
          description: BadRequest
          schema:
            $ref: '#/definitions/errorObject'
        '409':
          description: Conflict with existing capabilities
          schema:
            $ref: '#/definitions/errorObject'
          examples:
            application/json: { "message": "A capability with the name:'{name}' already exits, please give your capability a other name." }
  /capabilities/{capabilityId}:
    get:
      summary: Returns a single capability
      tags:
        - capability
      parameters:
        - in: path
          name: capabilityId
          type: string
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/capability-details'
    put:
      summary: Update the info fields on a single capability
      tags:
        - capability
      parameters:
        - in: path
          name: capabilityId
          type: string
          required: true
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/capability'
        '400':
          description: BadRequest
          schema:
            $ref: '#/definitions/errorObject'
        '404':
          description: Not found
    delete:
      summary: Deletes a capability 
      tags:
        - capability
      parameters:
        - in: path
          name: capabilityId
          required: true
          type: string
      responses:
        '200':
          description: Ok
        '404':
          description: Not Found
  /capabilities/{capabilityId}/members:
    post:
      summary: Adds a person to a capability 
      tags:
        - membership
      parameters:
        - in: path
          name: capabilityId
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
      responses:
        '200':
          description: Ok
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/errorObject'
  /capabilities/{capabilityId}/members/{email}:
    delete:
      summary: Deletes a person from a capability 
      tags:
        - membership
      parameters:
        - in: path
          name: capabilityId
          required: true
          type: string
        - in: path
          name: email
          type: string
          required: true
      responses:
        '200':
          description: Ok
        '404':
          description: Not Found
  /capabilities/{capabilityId}/contexts:
    post:
      summary: Adds a context to a capability 
      tags:
        - context
      parameters:
        - in: path
          name: capabilityId
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
      responses:
        '200':
          description: Ok
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/errorObject'
  /capabilities/{capabilityId}/topics:
    post:
      summary: Adds a topic to a capability 
      tags:
        - topic
      parameters:
        - in: path
          name: capabilityId
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              isPrivate:
                type: boolean
      responses:
        '200':
          description: Ok
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/errorObject'
  /topics:
    get:
      summary: Returns a list of all topics
      tags:
        - topic
      responses:
        '200':
          description: Ok
          schema:
            type: object
            properties:
              items:
                type: array
                items: 
                  $ref: '#/definitions/topic'
  /topics/{topicId}:
    get:
      summary: Returns a single topic
      tags:
        - topic
      parameters:
        - in: query
          name: topicId
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/topic'
        '404':
          description: Not Found
    put:
      summary: Updates a single topic
      tags:
        - topic
      parameters:
        - in: query
          name: topicId
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              isPrivate:
                type: boolean
      responses:
        '204':
          description: No Content
          # schema:
          #   $ref: '#/definitions/topic'
        '400':
          description: Bad Request
        '404':
          description: Not Found
  /topics/{topicId}/messageContracts:
    get:
      summary: Returns all message contracts for a single topic
      tags:
        - topic
      parameters:
        - in: query
          name: topicId
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/messageContract'
        '404':
          description: Not Found
  /topics/{topicId}/messageContracts/{type}:
    put:
      summary: Adds or updates a message contract on a single topic
      tags:
        - topic
      parameters:
        - in: query
          name: topicId
          required: true
          type: string
        - in: query
          name: type
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              description:
                type: string
              content:
                type: string
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
    delete:
      summary: Deletes a message contracts from a topic
      tags:
        - topic
      parameters:
        - in: query
          name: topicId
          required: true
          type: string
        - in: query
          name: type
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
  /kafka/environments/:
    get:
      summary: List of all environment names
      tags:
        - kafka
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: string
          examples:
            example-1:
              - enterprise
              - test
      operationId: get-kafka-environments
      parameters: []
  'kafka/{environmentName}/topics':
    get:
      summary: Returns a list of all topics in a given environment
      responses:
        '200':
          description: Ok
          schema:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                capabilityId:
                  type: string
                partitions:
                  type: integer
      parameters:
        - type: string
          in: query
          name: capabilityId
          description: filters topics by capability id
      description: ''
      tags:
        - kafka
    post:
      summary: ''
      operationId: post-topics
      responses:
        '200':
          description: OK
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              capabilityId:
                type: string
              partitions:
                type: integer
                default: 3
                minimum: 1
                maximum: 12
      tags:
        - kafka
    parameters:
      - type: string
        name: environmentName
        in: path
        required: true
  'kafka/{environmentName}/api-keys':
    parameters:
      - type: string
        name: environmentName
        in: path
        required: true
    get:
      summary: ''
      operationId: get-capabilities-capabilityId-kafka-api-keys
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                key:
                  type: string
                description:
                  type: string
      parameters:
        - type: string
          in: query
          name: capabilityId
          description: filters api keys by capability id
      description: ''
      tags:
        - kafka
    post:
      summary: ''
      operationId: postkafka-api-keys
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              key:
                type: string
              secret:
                type: string
      tags:
        - kafka
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              capabilityId:
                type: string
              description:
                type: string
  '/kafka/{environmentName}/api-keys/{key}':
    parameters:
      - type: string
        name: environmentName
        in: path
        required: true
      - type: string
        name: key
        in: path
        required: true
    delete:
      summary: ''
      operationId: delete-kafka-environmentName-api-keys-key
      responses:
        '200':
          description: OK
      tags:
        - kafka
definitions:
  capability-list:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/capability'
  capability:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      rootId:
        type: string
      members:
        type: array
        items:
          $ref: '#/definitions/member'
      contexts:
        type: array
        items:
          $ref: '#/definitions/context'
  capability-details:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      rootId:
        type: string
      members:
        type: array
        items:
          $ref: '#/definitions/member'
      contexts:
        type: array
        items:
          $ref: '#/definitions/context'
      topics:
        type: array
        items:
          $ref: '#/definitions/topic'
  member:
    type: object
    properties:
      email:
        type: string
  context:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      awsAccountId:
        type: string
      awsRoleArn:
        type: string
      awsRoleEmail:
        type: string
  errorObject:
    type: object
    properties:
      message:
        type: string
  topic:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      isPrivate:
        type: boolean
      messageContracts:
        type: array
        items:
          $ref: '#/definitions/messageContract'
  messageContract:
    type: object
    properties:
      type:
        type: string
      description:
        type: string
      content:
        type: string
