apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: team-service
  namespace: $(kubernetes-namespace)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-service
  template:
    metadata:
      labels:
        app: team-service
    spec:
      containers:
      - name: team-service
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/team-service:$(Build.BuildId)
        ports:
        - containerPort: 5000
        env:
          - name:  AWS_COGNITO_ACCESS_KEY
            value: $(AWS_COGNITO_ACCESS_KEY)
          - name:  AWS_COGNITO_SECRET_ACCESS_KEY
            value: $(AWS_COGNITO_SECRET_ACCESS_KEY)
          - name:  AWS_COGNITO_USER_POOL_ID
            value: $(AWS_COGNITO_USER_POOL_ID)
          - name: AWS_COGNITO_LOGIN_PROVIDER_NAME
            value: $(AWS_COGNITO_LOGIN_PROVIDER_NAME)
          - name: AWS_COGNITO_IDENTITY_POOL_ID
            value: $(AWS_COGNITO_IDENTITY_POOL_ID)