apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: team-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-service
  template:
    metadata:
      labels:
        app: team-service
    spec:
      initContainers:
      - name: dbmigrations
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/team-service/dbmigrations:$(Build.BuildId)
        env:
        - name:  PGDATABASE
          value: ts
        - name:  PGHOST
          value: $(PGHOST)
        - name:  PGPORT
          value: "1433"
        - name:  PGUSER
          value: $(PGUSER)
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: team-service
              key: password
      containers:
      - name: team-service
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/team-service:$(Build.BuildId)
        ports:
        - containerPort: 80
          name: web
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: TEAM_DATABASE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: team-service
              key: connection-string
