apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: team-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-service
  template:
    metadata:
      labels:
        app: team-service
    spec:
      initContainers:
        - name: dbmigrations
          image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/team-service/dbmigrations:$(Build.BuildId)
          env:
          - name:  PGDATABASE
            value: teamservice
          - name:  PGHOST
            value: ded-teamservicedb.czgqd5dy5owa.eu-central-1.rds.amazonaws.com
          - name:  PGPORT
            value: "1433"
          - name:  PGUSER
            value: $(PGUSER)
          - name:  PGPASSWORD
            value: $(PGPASSWORD)
      containers:
      - name: team-service
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/team-service:$(Build.BuildId)
        ports:
        - containerPort: 80
          name: web
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name:  AWS_COGNITO_ACCESS_KEY
          value: $(AWS_COGNITO_ACCESS_KEY)
        - name:  AWS_COGNITO_SECRET_ACCESS_KEY
          value: $(AWS_COGNITO_SECRET_ACCESS_KEY)
        - name:  AWS_COGNITO_USER_POOL_ID
          value: $(AWS_COGNITO_USER_POOL_ID)
        - name: AWS_COGNITO_LOGIN_PROVIDER_NAME
          value: $(AWS_COGNITO_LOGIN_PROVIDER_NAME)
        - name: AWS_COGNITO_IDENTITY_POOL_ID
          value: $(AWS_COGNITO_IDENTITY_POOL_ID)
        - name: TEAM_DATABASE_CONNECTIONSTRING
          value: $(TEAM_DATABASE_CONNECTIONSTRING)
        - name: AWS_ACCOUNT_ID
          value: "$(AWS_ACCOUNT_ID)"
