apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: capability-service
  namespace: $(kubernetes-namespace)
  labels:
    project: selfservice
    department: devex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capability-service
  template:
    metadata:
      labels:
        app: capability-service
        project: selfservice
        department: devex
    spec:
      initContainers:
      - name: dbmigrations
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/capability-service/dbmigrations:$(Build.BuildId)
        env:
        - name:  PGDATABASE
          value: ts
        - name:  PGHOST
          value: $(PGHOST)
        - name:  PGPORT
          value: "1433"
        - name:  PGUSER
          value: $(PGUSER)
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: capability-service-db
              key: password
      containers:
      - name: capability-service
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/capability-service:$(Build.BuildId)
        ports:
        - containerPort: 80
          name: web
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: IAMROLESERVICE_URL
          value: http://iamroleservice
        - name: ROLEMAPPERSERVICE_URL
          value: http://rolemapper-service
        - name: CAPABILITYSERVICE_DATABASE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: capability-service-db
              key: connection-string
        - name: CAPABILITY_SERVICE_KAFKA_BOOTSTRAP_SERVERS
          value: $(KAFKA_BOOTSTRAP_SERVERS)
        - name: CAPABILITY_SERVICE_KAFKA_BROKER_VERSION_FALLBACK
          value: "0.10.0.0"
        - name: CAPABILITY_SERVICE_KAFKA_API_VERSION_FALLBACK_MS
          value: "0"
        # - name: CAPABILITY_SERVICE_KAFKA_SSL_CA_LOCATION
        #   value: 
        - name: CAPABILITY_SERVICE_KAFKA_SASL_USERNAME
          value: $(KAFKA_SASL_USERNAME)
        - name: CAPABILITY_SERVICE_KAFKA_SASL_PASSWORD
          value: $(KAFKA_SASL_PASSWORD)
        - name: CAPABILITY_SERVICE_KAFKA_SASL_MECHANISMS
          value: "PLAIN"
        - name: CAPABILITY_SERVICE_KAFKA_SECURITY_PROTOCOL
          value: "SASL_SSL"