apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blaster
  namespace: $(kubernetes-namespace)
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: tools.dfds.cloud
    http:
      paths:
      # - path: /$(environment)-blaster
      - path: /blaster
        backend:
          serviceName: blaster
          servicePort: external
  - host: app.dfds.cloud
    http:
      paths:
      # - path: /$(environment)-blaster
      - path: /blaster
        backend:
          serviceName: blaster
          servicePort: external