apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: team-service
  namespace: $(kubernetes-namespace)
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
    - host: app.dfds.cloud
      http:
        paths:
          - path: /team-service
            backend:
              serviceName: team-service
              servicePort: external
