apiVersion: v1
kind: Secret
metadata:
  name: teamservice-basic-authentication-credentials
  labels:
    project: selfservice
    department: devex
    app: team-service
type: Opaque
stringData:
  auth: "$(TEAMSERVICE_BASIC_AUTHENTICATION_CREDENTIALS)"