apiVersion: v1
kind: Secret
metadata:
  name: capabilityservice-basic-authentication-credentials
  labels:
    project: selfservice
    department: devex
    app: team-service
type: Opaque
stringData:
  auth: "$(CAPABILITYSERVICE_BASIC_AUTHENTICATION_CREDENTIALS)"