apiVersion: apps/v1
kind: Deployment
metadata:
  name: capability-service
  namespace: selfservice
spec:
  template:
    spec:
      initContainers:
      - name: dbmigrations
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/capability-service/dbmigrations:$(Build.BuildId)
        env:
        - name:  PGDATABASE
          value: ts
        - name:  PGHOST
          value: $(PGHOST)
        - name:  PGPORT
          value: "1433"
        - name:  PGUSER
          value: $(PGUSER)
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: 
              key: password