apiVersion: apps/v1
kind: Deployment
metadata:
  name: capability-service
  namespace: selfservice
  labels:
    project: selfservice
    department: devex
    app: capability-service
    component: capability-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: capability-service
  template:
    metadata:
      labels:
        app: capability-service
        project: selfservice
        department: devex
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      initContainers:
      - name: dbmigrations
        image: ded/capability-service/dbmigrations:latest
        env:
        - name:  PGDATABASE
          value: ts
        - name:  PGHOST
          value: capability-service-db
        - name:  PGPORT
          value: "5432"
        - name:  PGUSER
          value: postgres
        - name: PGPASSWORD
          value: p
        - name: LOCAL_DEVELOPMENT
          value: "1"
        - name: PGSSLMODE
          value: disable          
      containers:      
      - name: capability-service
        image: capability-service
        ports:
        - containerPort: 80
          name: web
        - containerPort: 8080
          name: metrics
        resources:
          requests:
            memory: "300Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "200m"
        env:
        - name: CAPABILITYSERVICE_DATABASE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: capability-service-db
              key: connection-string
        - name: CAPABILITY_SERVICE_BASIC_AUTH_USER_AND_PASS
          valueFrom:
            secretKeyRef:
              name: capabilityservice-basic-authentication-credentials
              key: auth
        - name: CAPABILITY_SERVICE_KAFKA_BOOTSTRAP_SERVERS
          value: kafka
        - name: CAPABILITY_SERVICE_KAFKA_BROKER_VERSION_FALLBACK
          value: "0.10.0.0"
        - name: CAPABILITY_SERVICE_KAFKA_API_VERSION_FALLBACK_MS
          value: "0"
        - name: CAPABILITY_SERVICE_KAFKA_GROUP_ID
          value: "build.selfservice.capability-service-consumer"
        - name: CAPABILITY_SERVICE_KAFKA_ENABLE_AUTO_COMMIT
          value: "false"
        - name: CAPABILITY_SERVICE_KAFKA_TOPIC_CAPABILITY
          value: "build.selfservice.events.capabilities"
        - name: CAPABILITY_SERVICE_KAFKA_TOPIC_TOPICS
          value: "build.selfservice.events.topics"
        - name: DOTNET_USE_POLLING_FILE_WATCHER
          value: "true"
        - name: KAFKAJANITOR_API_ENDPOINT
          value: "http://kafka-janitor"
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 5
          httpGet:
            port: web
            path: /healthz
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          httpGet:
            port: web
            path: /healthz
      - name: debug
        image: sequoiia/aws-playground:latest
        imagePullPolicy: Always
        command: ["sleep"]
        args: ["10d"]
        env:
          - name: TZ
            value: "Europe/Copenhagen"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      hostname: kafka
      containers:
      - image: spotify/kafka
        name: kafka
        env:
        - name: ADVERTISED_HOST
          value: kafka
        - name: ADVERTISED_PORT
          value: "9092"
        - name: AUTO_CREATE_TOPICS
          value: "true"
        ports:
        - containerPort: 9092

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: capability-service-db
  name: capability-service-db
  namespace: selfservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capability-service-db
  template:
    metadata:
      labels:
        app: capability-service-db
    spec:
      hostname: capability-service-db
      containers:
      - image: postgres:latest
        name: db
        env:
        - name:  POSTGRES_USER
          value: postgres
        - name:  POSTGRES_PASSWORD
          value: p
        ports:
        - containerPort: 5432