sequenceDiagram

    User ->> +CapabilityController: [http post] /api/capabilities
    Note over User, CapabilityController: body: {"name": "foo"}

    CapabilityController ->> +CapabilityApplicationService: CreateCapability("foo")

    activate CapabilityDBContext

    CapabilityApplicationService ->> +Capability: Create("foo")
    Capability -->> CapabilityApplicationService: capability
    CapabilityApplicationService ->> +CapabilityRepository: Add(capability)
    
    CapabilityRepository ->> CapabilityDBContext: Add(capability)
    CapabilityDBContext -->> CapabilityRepository: 
    CapabilityRepository ->> CapabilityDBContext: SaveChanges()
    CapabilityDBContext -->> CapabilityRepository: 
    CapabilityRepository -->> -CapabilityApplicationService: 

    deactivate CapabilityDBContext

    CapabilityApplicationService ->> +RoleHandler: CreateRoleFor(capability)

    RoleHandler ->> +IAMRoleService: [http post] /api/roles
    Note over RoleHandler,IAMRoleService: body: {"name: "foo"}
    IAMRoleService -->> -RoleHandler: 200 OK
    Note over RoleHandler,IAMRoleService: body: {"roleArn": "[aws arn]"}

    RoleHandler ->> +RoleMapperService: [http post] /api/roles
    Note over RoleHandler,RoleMapperService: body: {"roleName": "foo", "roleArn": "[aws arn]"}
    RoleMapperService -->> -RoleHandler: 200 OK

    RoleHandler -->> -CapabilityApplicationService: 

    CapabilityApplicationService -->> -CapabilityController: capability

    CapabilityController ->> CapabilityController: ConvertToDto(capability)
    deactivate Capability

    CapabilityController -->> -User: 201 Created
    Note over CapabilityController,User: body: ...capability content...