apiVersion: v1
kind: Secret
metadata:
  name: capabilityservice-basic-authentication-credentials
  labels:
    project: selfservice
    department: devex
    app: team-service
type: Opaque
stringData:
  auth: "$(CAPABILITYSERVICE_BASIC_AUTHENTICATION_CREDENTIALS)"

---
apiVersion: v1
kind: Secret
metadata:
  name: capabilityservice-kafka-credentials
  labels:
    project: selfservice
    department: devex
    app: team-service
type: Opaque
stringData:
  username: "$(KAFKA_SASL_USERNAME)"
  password: "$(KAFKA_SASL_PASSWORD)"

---
apiVersion: v1
kind: Secret
metadata:
  name: capability-service-db
data:
  connection-string: VXNlciBJRD1jYXBzdmM7UGFzc3dvcmQ9Y2Fwc3ZjO0hvc3Q9Y2Fwc3ZjLWRiLXBvc3RncmVzcWw7UG9ydD01NDMyO0RhdGFiYXNlPXRzOw==
  password: Y2Fwc3Zj
type: Opaque
