apiVersion: apps/v1
kind: Deployment
metadata:
  name: capability-service
  namespace: selfservice
spec:
  template:
    spec:
      initContainers:
      - name: dbmigrations
        image: ded/capability-service/dbmigrations:latest
        imagePullPolicy: Never
        env:
        - name:  PGDATABASE
          value: ts
        - name:  PGHOST
          value: capability-service-db
        - name:  PGPORT
          value: "5432"
        - name:  PGUSER
          value: postgres
        - name: PGPASSWORD
          value: p
        - name: LOCAL_DEVELOPMENT
          value: "1"
        - name: PGSSLMODE
          value: disable
      containers:      
      - name: capability-service
        image: ded/capability-service:latest
        imagePullPolicy: Never