---

apiVersion: v1
kind: Service
metadata:
  name: capability-service-db
  namespace: selfservice
  labels:
    app: capability-service-db
    project: selfservice
    department: devex
    component: capability-service-db
spec:
  ports:
  - name: db
    port: 5432
    targetPort: 5432
  selector:
    app: capability-service-db