apiVersion: v1
kind: Secret
metadata:
  name: capabilityservice-basic-authentication-credentials
  namespace: $(kubernetes-namespace)
stringData:
  auth: "demo:demo"

---
apiVersion: v1
kind: Secret
metadata:
  name: capabilityservice-kafka-credentials
  namespace: $(kubernetes-namespace)
stringData:
  username: "demo"
  password: "demo"
